name: Software Checks

on:
  push:
    branches: [ smf21, smf20, master ]
  pull_request:
    branches: [ smf21, smf20, master ]

  workflow_dispatch:
jobs:          
  check-signedoff:
    runs-on: ubuntu-latest
    name: Check Signed Off
    steps:
      - uses: actions/checkout@master
        with:
          submodules: false
      - name: Checking Sign off
        id: check-signoff
        run: php ./.github/scripts/check-signed-off.php github
  check-licensing:
    runs-on: ubuntu-latest
    name: Check Licensing
    steps:
      - uses: actions/checkout@master
        with:
          submodules: false
      - name: Checking Licensing
        id: check-licensing
        run: php ./.github/scripts/check-license-master.php ./
  check-eof:
    runs-on: ubuntu-latest
    name: Check End of File
    steps:
      - uses: actions/checkout@master
        with:
          submodules: false
      - name: Checking End of File
        id: check-eof
        run: php ./.github/scripts/check-eof-master.php ./